# Generated by Django 3.2.15 on 2022-08-22 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.RenameField(
            model_name='mailing',
            old_name='message',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='client',
            name='operators_code',
        ),
        migrations.AddField(
            model_name='client',
            name='operator_code',
            field=models.CharField(max_length=3, null=True, verbose_name='Код мобильного оператора'),
        ),
    ]
